name = "{{NAME}}"
version = "0.1.0"
description = "a web project"

target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
lustre = ">= 4.5.0 and < 5.0.0"

